/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "payload.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Payload, Payload, AUTO)


PB_BIND(Message, Message, AUTO)


PB_BIND(Sensors_uca_board, Sensors_uca_board, AUTO)





