/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_PAYLOAD_PB_H_INCLUDED
#define PB_PAYLOAD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Blockchain { 
    Blockchain_HYPERLEDGER_FABRIC = 0, 
    Blockchain_HYPERLEDGER_SAWTOOTH = 1, 
    Blockchain_SUBSTRATE = 2, 
    Blockchain_ETHEREUM = 3 
} Blockchain;

typedef enum _Action { 
    Action_SET_DATA = 0, 
    Action_GET_DATA = 1 
} Action;

/* Struct definitions */
typedef struct _Sensors_uca_board { 
    float temperature; 
    float altitude; 
    float pressure; 
    float axis_x; 
    float temperature2; 
    float altitude2; 
    float pressure2; 
    float axis_x2; 
    float temperature3; 
    float altitude4; 
    float pressure5; 
    float axis_x6; 
    float temperature4; 
    float altitude5; 
    float pressure6; 
    float axis_x7; 
} Sensors_uca_board;

typedef struct _Message { 
    Blockchain blockchain_id; 
    char smart_contract_name[13]; 
    Action action; 
    Sensors_uca_board sensors_uca_board; 
} Message;

typedef PB_BYTES_ARRAY_T(33) Payload_public_key_t;
typedef PB_BYTES_ARRAY_T(65) Payload_signature_t;
typedef struct _Payload { 
    Payload_public_key_t public_key; 
    Payload_signature_t signature; 
    Message message; 
} Payload;


/* Helper constants for enums */
#define _Blockchain_MIN Blockchain_HYPERLEDGER_FABRIC
#define _Blockchain_MAX Blockchain_ETHEREUM
#define _Blockchain_ARRAYSIZE ((Blockchain)(Blockchain_ETHEREUM+1))

#define _Action_MIN Action_SET_DATA
#define _Action_MAX Action_GET_DATA
#define _Action_ARRAYSIZE ((Action)(Action_GET_DATA+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Payload_init_default                     {{0, {0}}, {0, {0}}, Message_init_default}
#define Message_init_default                     {_Blockchain_MIN, "", _Action_MIN, Sensors_uca_board_init_default}
#define Sensors_uca_board_init_default           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Payload_init_zero                        {{0, {0}}, {0, {0}}, Message_init_zero}
#define Message_init_zero                        {_Blockchain_MIN, "", _Action_MIN, Sensors_uca_board_init_zero}
#define Sensors_uca_board_init_zero              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Sensors_uca_board_temperature_tag        1
#define Sensors_uca_board_altitude_tag           2
#define Sensors_uca_board_pressure_tag           3
#define Sensors_uca_board_axis_x_tag             4
#define Sensors_uca_board_temperature2_tag       5
#define Sensors_uca_board_altitude2_tag          6
#define Sensors_uca_board_pressure2_tag          7
#define Sensors_uca_board_axis_x2_tag            8
#define Sensors_uca_board_temperature3_tag       9
#define Sensors_uca_board_altitude4_tag          10
#define Sensors_uca_board_pressure5_tag          11
#define Sensors_uca_board_axis_x6_tag            12
#define Sensors_uca_board_temperature4_tag       13
#define Sensors_uca_board_altitude5_tag          14
#define Sensors_uca_board_pressure6_tag          15
#define Sensors_uca_board_axis_x7_tag            16
#define Message_blockchain_id_tag                1
#define Message_smart_contract_name_tag          2
#define Message_action_tag                       3
#define Message_sensors_uca_board_tag            4
#define Payload_public_key_tag                   1
#define Payload_signature_tag                    2
#define Payload_message_tag                      3

/* Struct field encoding specification for nanopb */
#define Payload_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    public_key,        1) \
X(a, STATIC,   REQUIRED, BYTES,    signature,         2) \
X(a, STATIC,   REQUIRED, MESSAGE,  message,           3)
#define Payload_CALLBACK NULL
#define Payload_DEFAULT NULL
#define Payload_message_MSGTYPE Message

#define Message_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    blockchain_id,     1) \
X(a, STATIC,   REQUIRED, STRING,   smart_contract_name,   2) \
X(a, STATIC,   REQUIRED, UENUM,    action,            3) \
X(a, STATIC,   REQUIRED, MESSAGE,  sensors_uca_board,   4)
#define Message_CALLBACK NULL
#define Message_DEFAULT NULL
#define Message_sensors_uca_board_MSGTYPE Sensors_uca_board

#define Sensors_uca_board_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    temperature,       1) \
X(a, STATIC,   REQUIRED, FLOAT,    altitude,          2) \
X(a, STATIC,   REQUIRED, FLOAT,    pressure,          3) \
X(a, STATIC,   REQUIRED, FLOAT,    axis_x,            4) \
X(a, STATIC,   REQUIRED, FLOAT,    temperature2,      5) \
X(a, STATIC,   REQUIRED, FLOAT,    altitude2,         6) \
X(a, STATIC,   REQUIRED, FLOAT,    pressure2,         7) \
X(a, STATIC,   REQUIRED, FLOAT,    axis_x2,           8) \
X(a, STATIC,   REQUIRED, FLOAT,    temperature3,      9) \
X(a, STATIC,   REQUIRED, FLOAT,    altitude4,        10) \
X(a, STATIC,   REQUIRED, FLOAT,    pressure5,        11) \
X(a, STATIC,   REQUIRED, FLOAT,    axis_x6,          12) \
X(a, STATIC,   REQUIRED, FLOAT,    temperature4,     13) \
X(a, STATIC,   REQUIRED, FLOAT,    altitude5,        14) \
X(a, STATIC,   REQUIRED, FLOAT,    pressure6,        15) \
X(a, STATIC,   REQUIRED, FLOAT,    axis_x7,          16)
#define Sensors_uca_board_CALLBACK NULL
#define Sensors_uca_board_DEFAULT NULL

extern const pb_msgdesc_t Payload_msg;
extern const pb_msgdesc_t Message_msg;
extern const pb_msgdesc_t Sensors_uca_board_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Payload_fields &Payload_msg
#define Message_fields &Message_msg
#define Sensors_uca_board_fields &Sensors_uca_board_msg

/* Maximum encoded size of messages (where known) */
#define Message_size                             101
#define Payload_size                             205
#define Sensors_uca_board_size                   81

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
